[package]
name = "aptos-indexer-transaction-generator"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
# used for localnode.
aptos = { workspace = true }
aptos-config = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
